### ISSUE TITLE
Error at omitted spaces/undocumented whitespace sensitivity (?)

### ISSUE THREAD

**Issue by mindbound** [pluskid/SimpleStructs.jl#3]
Omitting the space between the type name and the opening parenthesis causes a "wrong number of parameters" error.

![Screenshot](http://i.imgur.com/4QWxYss.png)

**Comment by Evizero** [comment]
of course it does. if you omit the space between `Struct2` and `(` then Julia thinks this is a function call. This is a property of the language.

**Comment by mindbound** [comment]
My bad. Thanks for clarification.

**Comment by Evizero** [comment]
But you do have a point though. It's not the most intuitive syntax. The goal of this macro is to be really concise.

**Comment by mindbound** [comment]
IMO a `begin .. end` syntax would be more intuitive and almost as concise, although I'm not sure how much extra work would it take to implement that.
