### ISSUE TITLE
Generate custom show

### ISSUE THREAD

**Issue by Evizero** [pluskid/SimpleStructs.jl#4]
Just an idea

The following code 

``` Julia
@defstruct MyType (
    alpha::Int = 0.2,
    beta::String = "Hello"
)

MyType()
```

could produce something like

```
MyType(alpha=0.2, beta="Hello")
```

or

```
MyType
  - alpha = 0.2
  - beta  = "Hello"
```

**Comment by pluskid** [comment]
I think the first is preferred. The second quickly become messy and too complicated (a full pretty-print implementation) when the fields are composite types.

**Comment by Evizero** [comment]
I agree. Although it might be nice to generate a `prettyprint` or `dump` function for the second one

**Comment by pluskid** [comment]
`show` function added. But I'm not sure about more complicated dump function. I guess they should be easy to implement if Julia has proper built-in API to handle nested indentation, etc.

**Comment by Evizero** [comment]
cool thanks. yes, you are probably right
